#!/usr/bin/env bash
#
# Does upkeep, run discogs_update.py before running this.
# Not including that here because the spreadsheet needs
# to be sorted before running this

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

echo "Reminder: Run 'nextalbums discogs-update' and sort the spreadsheet online by Year, then Album Name"
cd "$THIS_DIR" || exit 1
echo "Generating csv..."
nextalbums generate-csv
echo "Creating SQL statements..."
nextalbums create-sql-statements
nextalbums create-sql-statements -s
echo "(use sudo password)"
echo "updating albums..."
sudo mysql <./sql_data/statements.sql
echo "updating scorealbums..."
sudo mysql <./sql_data/score_statements.sql
echo "Updating src csv files..."
nextalbums update-csv-datafiles
