#!/usr/bin/env bash
#
# Does upkeep, run discogs_update.py before running this.
# Not including that here because the spreadsheet needs
# to be sorted before running this

set -o pipefail
set -u

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit 1

# settings.py prints eval-able output
eval "$(python3 settings.py)" || exit $?

echo "Reminder: Run 'nextalbums discogs-update' and sort the spreadsheet online by Year, then Album Name"
echo "Generating csv..."
nextalbums generate-csv
echo "Creating SQL statements..."
nextalbums create-sql-statements
nextalbums create-sql-statements -s
echo "updating albums..."
mysql -u "${MYSQL_DATABASE_USERNAME}" -p"${MYSQL_DATABASE_PASSWORD}" <./sql_data/statements.sql
echo "updating scorealbums..."
mysql -u "${MYSQL_DATABASE_USERNAME}" -p"${MYSQL_DATABASE_PASSWORD}" <./sql_data/score_statements.sql
echo "Updating src csv files..."
nextalbums update-csv-datafiles
