#!/bin/bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

# update from remote
git pull

# run server
pipenv install
exec pipenv run python3 "${THIS_DIR}/app.py"
